/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Коптра",
  "tagline": "Полное руководство по использованию",
  "favicon": "img/coptra-icon.png",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://etaiee.github.io",
  "baseUrl": "/CoptraDocs/",
  "trailingSlash": true,
  "organizationName": "Etaiee",
  "projectName": "CoptraDocs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/etaiee/CoptraDocs/edit/main/",
          "routeBasePath": "/"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/etaiee/CoptraDocs/edit/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en",
          "ru"
        ],
        "indexDocs": true,
        "indexBlog": true,
        "docsRouteBasePath": "/",
        "blogRouteBasePath": "/blog",
        "searchBarPosition": "right"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Логотип Коптра",
        "src": "img/logo.png",
        "href": "https://coptra.x10.mx",
        "target": "_self"
      },
      "items": [
        {
          "href": "https://coptra.x10.mx",
          "label": "Главная",
          "position": "left",
          "target": "_self",
          "activeBaseRegex": "^/$"
        },
        {
          "href": "https://coptra.x10.mx/products.php",
          "label": "Продукты",
          "position": "left",
          "target": "_self"
        },
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Документация"
        },
        {
          "href": "https://coptra.x10.mx/blog.php",
          "label": "Блог",
          "position": "left",
          "target": "_self"
        },
        {
          "href": "https://coptra.x10.mx/contacts.php",
          "label": "Контакты",
          "position": "left",
          "target": "_self"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Информация",
          "items": [
            {
              "label": "Блог",
              "href": "https://coptra.x10.mx/blog.php",
              "target": "_self"
            },
            {
              "label": "Контакты",
              "href": "https://coptra.x10.mx/contacts.php",
              "target": "_self"
            },
            {
              "label": "Документация",
              "to": "/"
            }
          ]
        },
        {
          "title": "Продукты",
          "items": [
            {
              "label": "Сельское хозяйство",
              "href": "https://coptra.x10.mx/products.php#agriculture",
              "target": "_self"
            },
            {
              "label": "Образование",
              "href": "https://coptra.x10.mx/products.php#educational",
              "target": "_self"
            },
            {
              "label": "FPV Дроны",
              "href": "https://coptra.x10.mx/products.php#fpv",
              "target": "_self"
            },
            {
              "label": "Грузоперевозки",
              "href": "https://coptra.x10.mx/products.php#cargo",
              "target": "_self"
            },
            {
              "label": "Компоненты",
              "href": "https://coptra.x10.mx/products.php#components",
              "target": "_self"
            }
          ]
        },
        {
          "title": "Конфигуратор",
          "items": [
            {
              "label": "Скачать для Windows",
              "href": "https://coptra.x10.mx/api/configurator/download.php?version=1.1.0&platform=windows&file=Coptra-Configurator_win32_x64_1.1.0.msi",
              "target": "_self"
            },
            {
              "label": "Скачать для Linux",
              "href": "https://coptra.x10.mx/api/configurator/download.php?version=1.1.0&platform=linux&file=Coptra-Configurator_linux_x64_1.1.0.zip",
              "target": "_self"
            }
          ]
        },
        {
          "title": "Свяжитесь с нами",
          "items": [
            {
              "label": "info@coptra.ru",
              "href": "mailto:info@coptra.ru"
            },
            {
              "label": "+7 (123) 456-78-90",
              "href": "tel:+71234567890"
            },
            {
              "html": "\n                  <div class=\"social-icons\">\n                    <a href=\"#\" target=\"_blank\" rel=\"noopener noreferrer\" aria-label=\"VK\" class=\"social-icon\">\n                      <img src=\"/CoptraDocs/img/vk.svg\" alt=\"VK\" width=\"16\" height=\"16\" />\n                    </a>\n                    <a href=\"#\" target=\"_blank\" rel=\"noopener noreferrer\" aria-label=\"Telegram\" class=\"social-icon\">\n                      <img src=\"/CoptraDocs/img/telegram.svg\" alt=\"Telegram\" width=\"16\" height=\"16\" />\n                    </a>\n                    <a href=\"#\" target=\"_blank\" rel=\"noopener noreferrer\" aria-label=\"YouTube\" class=\"social-icon\">\n                      <img src=\"/CoptraDocs/img/youtube.svg\" alt=\"YouTube\" width=\"16\" height=\"16\" />\n                    </a>\n                  </div>\n                "
            }
          ]
        }
      ],
      "copyright": "© 2025 Коптра. Все права защищены."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
